<?php
  include_once  'Modal/modal_template.php';
?>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<div class="container-fluid h-100">
	<div class="row h-100">
    
    <div class="col-md-6 banner">
    	<div class="row h-100 justify-content-center align-items-center">
    		<div>
				<div class="communicationItem">
					<i class="fas fa-search fa-2x mr-3"></i>
					Siga o que lhe interessa.
				</div>
				<div class="communicationItem">
					<i class="fas fa-user-friends fa-2x mr-3"></i>
					Saiba sobre o que as pessoas estão falando.
				</div>
				<div class="communicationItem">
					<i class="far fa-comment fa-2x mr-3"></i>
					Participe da conversa.
				</div>
			</div>
		</div>
    </div>

    <div class="col-md-6 pt-4 pl-5 pr-5">
		<form method="post" action="autenticar">
			<div class="row">
				<div class="col">
					<input type="text" name="email" class="form-control" placeholder="E-mail">
				</div>
				<div class="col">
					<input type="password" name="senha" class="form-control" placeholder="Senha">
				</div>
				<div class="col-auto">
					<button type="submit" class="btn btn-primary mb-2">Entrar</button>
				</div>
			</div>
		</form>
		<?php
        if ($this->view->login == 'erro'){
        ?>
        <script>showModal('Falha na autenticação!', 'E-mail e(ou) senha estão incorretos!!', 'bg-danger');</script>
		<?php
		}?>
		<?php
        if ($this->view->login == 'erro2'){
        ?>
        <script>showModal('Inscreva-se ou Cadastre-se', 'Não é possível acessar esta página!', 'bg-danger');</script>
		<?php
		}?>
		<?php
		if (isset($_GET['logout']) && $_GET['logout'] == 'true'){
        ?>
        <script>showModal('Volte sempre', 'Obrigado por visitar o Twitter do SK','bg-success');</script>
		<?php
		}?>
		<div class="row pt-5 pl-5 pr-5">
			<div class="col pl-5 pr-5">
				<img src="/img/twitter_logo.png" />
				<h1 class="title">Veja o que está acontecendo no mundo agora</h1>

				<h2 class="mt-5 subtitle">Participe hoje do Twitter.</h2>
				<a href="/inscreverse" class="btn btn-primary btn-block mb-2">Inscrever-se</a>
			</div>	
		</div>


    </div>

  </div>
</div>