<?php
  include_once  'Modal/modal_template.php';
?>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/registrar" method="post">
              <div class="form-group">
                <input type="text" value="<?= $this->view->usuario['nome']?>" name="nome" class="form-control" placeholder="Nome">
              </div>
              
              <div class="form-group">
                <input type="text" value="<?= $this->view->usuario['email']?>" name="email" class="form-control" placeholder="E-mail">
              </div>

              <div class="form-group">
                <input type="password" value="<?= $this->view->usuario['senha']?>" name="senha" class="form-control" placeholder="Senha">
              </div>
              
              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                </small>
              </div>
              <button type="submit" class="btn btn-primary btn-block">Inscrever-se</button>
              <a class="btn btn-info btn-block" href="/">Fazer Login</a>
              
              <?php
                if ($this->view->erroCadastro == 'errnome'){
              ?>
              <script>showModal('Nome incorreto!', 'Ensira um nome correto!!', 'bg-danger');</script>
              <?php
              }
              ?>

              <?php
                if ($this->view->erroCadastro == 'erremail'){
              ?>
              <script>showModal('E-mail está errado!!', 'Ensira um e-mail correto!!', 'bg-danger');</script>";
              <?php
              }
              ?>

              <?php
              if ($this->view->erroCadastro == 'usuarioexistente'){
              ?>
              <script>showModal('E-mail existente no Twitter!', 'Ensira um e-mail novo ou faça o login caso já possua cadastro!!', 'bg-info');</script>
              <?php
              }?>

              <?php
                if ($this->view->erroCadastro == 'errsenha'){
              ?>
              <script>showModal('Senha está errada!!', 'Senha precisa ter no mínimo 9 caracteres: 1 minúsculo, 1 maiúsculo, 1 caracter especial e 1 número', 'bg-warning');</script>
              <?php
              }
              ?>

            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



    
  